### ISSUE TITLE
Jupyter Notebook environment issue in some (hydroshare) accounts

### ISSUE THREAD

**Issue by laurencelin** [hydroshare/hydroshare-jupyterhub#36]
I was developing and running RHESSys Jupyter notebook on NSCA server (Python 2 kernel).  This notebook relies on python-based Workflows (developed by Brian Miles). In my case, some of the Workflows commands cannot be executed within the Jupyter notebook (error message is attached below) but was able to do so in the virtual machine terminal.  I found a solution to this when I created a new hydroshare account and link to Jupyter notebook on NSCA server. The same commands were able to run in both Jupyter Notebook environment and the virtual machine terminal under my new account. 

python library file lists in notebook/utilities directory in old and new accounts were attached.
[new_account_python_lib.txt](https://github.com/hydroshare/hydroshare-jupyterhub/files/745704/new_account_python_lib.txt)
[old_account_python_lib.txt](https://github.com/hydroshare/hydroshare-jupyterhub/files/745705/old_account_python_lib.txt)

-------------- error message when running "!GenerateLandcoverMaps.py -p /home/jovyan/work/notebooks/data/cwtB/cwtB --skipRoads --overwrite" within Jupyter notebook cell:
Traceback (most recent call last):
  File "/opt/conda/envs/python2/bin/GenerateLandcoverMaps.py", line 4, in <module>
    __import__('pkg_resources').run_script('rhessysworkflows==1.34', 'GenerateLandcoverMaps.py')
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/rhessysworkflows-1.34-py2.7.egg/EGG-INFO/scripts/GenerateLandcoverMaps.py", line 167, in <module>
    params = importlib.import_module('rhessys.params')
  File "/opt/conda/envs/python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named params

**Comment by Castronova** [comment]
old issue. closing.
