### ISSUE TITLE
Error creating hydroshare resource

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare-jupyterhub#41]
Basic timeseries analysis notebook.

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jovyan/work/notebooks/utilities/hydroshare/threads.py", line 23, in f
    res = self.func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/hs_restclient-1.2.6-py3.5.egg/hs_restclient/__init__.py", line 904, in createResource
    close_fd = self._prepareFileForUpload(params, resource_file, resource_filename)
  File "/opt/conda/lib/python3.5/site-packages/hs_restclient-1.2.6-py3.5.egg/hs_restclient/__init__.py", line 229, in _prepareFileForUpload
```

**Comment by Castronova** [comment]
Some thing with the timeseries resource example

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/conda/envs/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/conda/envs/python2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jovyan/work/notebooks/utilities/hydroshare/threads.py", line 23, in f
    res = self.func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/hs_restclient/__init__.py", line 904, in createResource
    close_fd = self._prepareFileForUpload(params, resource_file, resource_filename)
  File "build/bdist.linux-x86_64/egg/hs_restclient/__init__.py", line 229, in _prepareFileForUpload
    raise HydroShareArgumentException("{0} is not a file or is not readable.".format(resource_file))
```
