### ISSUE TITLE
Timeseries resource library is broken

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare-jupyterhub#42]
The timeseries resource needs to be updated.

```
Failed to retrieve resource content from HydroShare: hydroshare instance has no attribute '_getResourceFromHydroShare'
```

**Comment by Castronova** [comment]
Some thing with the timeseries resource example

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/conda/envs/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/conda/envs/python2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jovyan/work/notebooks/utilities/hydroshare/threads.py", line 23, in f
    res = self.func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/hs_restclient/__init__.py", line 904, in createResource
    close_fd = self._prepareFileForUpload(params, resource_file, resource_filename)
  File "build/bdist.linux-x86_64/egg/hs_restclient/__init__.py", line 229, in _prepareFileForUpload
    raise HydroShareArgumentException("{0} is not a file or is not readable.".format(resource_file))
```
